blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ğŸ½â€â™€ï¸ Getting help with code
    url: https://github.com/netreconlab/Parse-Swift/discussions
    about: Get help with code-level questions on Github Discussions.
  - name: ğŸ™‹ Getting general help
    url: https://github.com/netreconlab/Parse-Swift/discussions
    about: Get help with other questions on Github Discussions.
